import importlib.util
import pathlib
import sys
import types

import pytest


def _load_generator_module():
    path = (
        pathlib.Path(__file__).resolve().parents[1]
        / "scripts"
        / "generate_torch_ops.py"
    )
    spec = importlib.util.spec_from_file_location("generate_torch_ops_under_test", path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)

    return module


def test_select_op_names_honors_slot_8_and_legacy_headers():
    module = _load_generator_module()
    config = {
        "default_all": {"headers": None, "implementations": None},
        "default_native": {"headers": None, "implementations": (0,)},
        "explicit_torch": {"headers": None, "implementations": (8,)},
        "legacy": {"headers": ["legacy.h"], "implementations": None},
    }

    assert module._select_op_names(
        None,
        ["default_all", "default_native"],
        config,
    ) == ["default_all", "explicit_torch"]
    assert module._select_op_names(
        ["explicit_torch"],
        ["default_all", "default_native"],
        config,
    ) == ["explicit_torch"]


def test_select_op_names_maps_public_names_to_aten_names():
    module = _load_generator_module()
    config = {
        "div": {"headers": None, "implementations": (8,)},
        "internal_log_softmax": {"headers": None, "implementations": (8,)},
    }

    assert module._select_op_names(
        None,
        ["div", "div_", "_log_softmax"],
        config,
    ) == ["div", "div_", "_log_softmax"]


def test_load_aten_entries_uses_packaged_torchgen(monkeypatch):
    module = _load_generator_module()
    entries = [{"func": "relu.out(Tensor self, *, Tensor(a!) out) -> Tensor(a!)"}]
    monkeypatch.setattr(module, "_load_packaged_aten_entries", lambda: (entries, True))

    assert module._load_aten_entries("v9.9.9") == entries


def test_packaged_aten_entries_include_autogenerated_out_variants():
    module = _load_generator_module()
    entries, expanded_autogen = module._load_packaged_aten_entries()

    if not expanded_autogen:
        pytest.skip("installed torchgen does not support autogen expansion")

    relu_out_entry = next(
        entry
        for entry in module._find_out_entries(entries, "relu")
        if entry["func"].startswith("relu.out(")
    )

    assert module._parse_func(relu_out_entry["func"]).out_params


def test_packaged_aten_entries_fall_back_when_tags_are_missing(
    monkeypatch, tmp_path, capsys
):
    module = _load_generator_module()
    native_dir = tmp_path / "packaged" / "ATen" / "native"
    native_dir.mkdir(parents=True)
    native_path = native_dir / "native_functions.yaml"
    native_path.write_text(
        "- func: add.out(Tensor self, Tensor other, *, Tensor(a!) out) -> Tensor(a!)\n"
    )
    spec = types.SimpleNamespace(submodule_search_locations=[str(tmp_path)])
    monkeypatch.setattr(module.importlib.util, "find_spec", lambda name: spec)

    entries, expanded_autogen = module._load_packaged_aten_entries()

    assert expanded_autogen is False
    assert entries == [
        {"func": "add.out(Tensor self, Tensor other, *, Tensor(a!) out) -> Tensor(a!)"}
    ]
    assert "using explicit schemas only" in capsys.readouterr().err


def test_public_op_name_normalizes_aten_internal_and_inplace_names():
    module = _load_generator_module()

    assert module._public_op_name("_softmax") == "internal_softmax"
    assert module._public_op_name("add_") == "add"
    assert module._public_op_name("_add_relu_") == "internal_add_relu"


def test_schema_self_param_renders_as_input_in_public_cpp_api():
    module = _load_generator_module()
    op = module._parse_func(
        "_softmax(Tensor self, int dim, bool half_to_float, *, "
        "Tensor(a!) out) -> Tensor(a!)"
    )

    assert op.params[0].name == "self"
    assert op.params[0].api_name == "input"

    base = module._generate_base_header("internal_softmax", [op])
    source = module._generate_torch_method_source("internal_softmax", op)

    assert "Softmax(const Tensor input, const int64_t dim" in base
    assert "self_shape_" not in base
    assert "input_shape_" in base
    assert "auto at_self = ToAtenTensor<kDev>" in source
    assert "input_shape_" in source
    assert "at::_softmax_out(at_out, at_self" in source


def test_torch_source_uses_existing_c10_stream_guards():
    module = _load_generator_module()
    op = module._parse_func("abs.out(Tensor self, *, Tensor(a!) out) -> Tensor(a!)")

    method = module._generate_torch_method_source("abs", op)
    source = module._generate_torch_source("abs", [op])

    assert "stream_ == nullptr" not in method
    assert "C10<kDev>::GetStreamFromExternal(stream_, device_index)" in method

    for device in ("nvidia", "cambricon", "metax", "moore", "iluvatar"):
        assert f'#include "torch/{device}/c10.h"' in source

    for device in ("cpu", "ascend", "hygon"):
        assert f'#include "torch/{device}/c10.h"' not in source


def test_optional_tensor_params_are_exposed_and_forwarded_to_aten():
    module = _load_generator_module()
    op = module._parse_func(
        "batch_norm_elemt(Tensor input, Tensor? weight=None, "
        "Tensor? bias=None, Tensor mean, Tensor invstd, float eps, "
        "*, Tensor(a!) out) -> Tensor(a!)"
    )

    assert [param.cpp_type for param in op.visible_params] == [
        "Tensor",
        "std::optional<Tensor>",
        "std::optional<Tensor>",
        "Tensor",
        "Tensor",
        "double",
        "Tensor",
    ]

    base = module._generate_base_header("batch_norm_elemt", [op])
    source = module._generate_torch_method_source("batch_norm_elemt", op)

    assert "#include <optional>" in base
    assert "std::optional<Tensor> weight" in base
    assert "std::optional<Tensor> bias" in base
    assert "bool has_weight_" in base
    assert "bool has_bias_" in base
    assert (
        "weight_shape_{weight ? Tensor::Shape{weight->shape()} : Tensor::Shape{}}"
        in base
    )
    assert (
        "weight_strides_{weight ? Tensor::Strides{weight->strides()} "
        ": Tensor::Strides{}}" in base
    )
    assert "c10::optional<at::Tensor> at_weight" in source
    assert "c10::optional<at::Tensor> at_bias" in source
    assert "weight->shape()" in source
    assert "weight_shape_" not in source
    assert "at::batch_norm_elemt_out" in source
    assert "at_weight" in source
    assert "at_bias" in source


def test_tensor_list_params_are_exposed_and_forwarded_to_aten():
    module = _load_generator_module()
    op = module._parse_func(
        "stack(Tensor[] tensors, int dim=0, *, Tensor(a!) out) -> Tensor(a!)"
    )

    assert [param.cpp_type for param in op.visible_params] == [
        "std::vector<Tensor>",
        "int64_t",
        "Tensor",
    ]
    assert op.is_testable

    base = module._generate_base_header("stack", [op])
    source = module._generate_torch_method_source("stack", op)

    assert "#include <vector>" in base
    assert "std::vector<Tensor> tensors" in base
    assert "std::vector<at::Tensor> at_tensors" in source
    assert "at_tensors.reserve(tensors.size())" in source
    assert "for (const auto& tensor : tensors)" in source
    assert "at::stack_out(at_out, at_tensors, dim)" in source


def test_optional_tensor_list_params_are_exposed_and_forwarded_to_aten():
    module = _load_generator_module()
    op = module._parse_func(
        "index.Tensor_out(Tensor self, Tensor?[] indices, "
        "*, Tensor(a!) out) -> Tensor(a!)"
    )

    assert [param.cpp_type for param in op.visible_params] == [
        "Tensor",
        "std::vector<std::optional<Tensor>>",
        "Tensor",
    ]

    source = module._generate_torch_method_source("index", op)

    assert "c10::List<c10::optional<at::Tensor>> at_indices" in source
    assert "for (const auto& tensor : indices)" in source
    assert "at_indices.push_back(c10::nullopt)" in source
    assert "at::index_out(at_out, at_self, at_indices)" in source


def test_optional_scalar_and_array_params_are_exposed_and_forwarded_to_aten():
    module = _load_generator_module()
    quantile = module._parse_func(
        "quantile(Tensor input, Tensor q, int? dim=None, bool keepdim=False, "
        "str interpolation='linear', *, Tensor(a!) out) -> Tensor(a!)"
    )
    upsample = module._parse_func(
        "upsample_bicubic2d(Tensor input, SymInt[2] output_size, "
        "bool align_corners, float[]? scale_factors=None, "
        "*, Tensor(a!) out) -> Tensor(a!)"
    )

    assert [param.cpp_type for param in quantile.visible_params] == [
        "Tensor",
        "Tensor",
        "std::optional<int64_t>",
        "bool",
        "std::string",
        "Tensor",
    ]
    assert [param.cpp_type for param in upsample.visible_params] == [
        "Tensor",
        "std::vector<int64_t>",
        "bool",
        "std::optional<std::vector<double>>",
        "Tensor",
    ]

    quantile_source = module._generate_torch_method_source("quantile", quantile)
    upsample_source = module._generate_torch_method_source(
        "upsample_bicubic2d", upsample
    )

    assert "c10::optional<int64_t> at_dim" in quantile_source
    assert "at::quantile_out" in quantile_source
    assert "at_dim" in quantile_source
    assert "c10::optional<at::ArrayRef<double>> at_scale_factors" in upsample_source
    assert "at::upsample_bicubic2d_out" in upsample_source
    assert "at_scale_factors" in upsample_source


def test_required_scalar_type_params_use_public_data_type():
    module = _load_generator_module()
    op = module._parse_func(
        "_softmax_backward_data(Tensor grad_output, Tensor output, int dim, "
        "ScalarType input_dtype, *, Tensor(a!) grad_input) -> Tensor(a!)"
    )

    assert [param.cpp_type for param in op.visible_params] == [
        "Tensor",
        "Tensor",
        "int64_t",
        "DataType",
        "Tensor",
    ]

    source = module._generate_torch_method_source("internal_softmax_backward_data", op)

    assert "at::_softmax_backward_data_out" in source
    assert "ToAtenDataType(input_dtype)" in source


def test_existing_base_overload_can_omit_optional_schema_params():
    module = _load_generator_module()
    op = module._parse_func(
        "slow_conv3d(Tensor input, Tensor weight, int[3] kernel_size, "
        "Tensor? bias=None, int[3] stride=1, int[3] padding=0, "
        "*, Tensor(a!) out) -> Tensor(a!)"
    )
    signature = [
        ("Tensor", "input"),
        ("Tensor", "weight"),
        ("std::vector<int64_t>", "kernel_size"),
        ("std::vector<int64_t>", "stride"),
        ("std::vector<int64_t>", "padding"),
        ("Tensor", "out"),
    ]

    bound = module._bind_base_signature(op, signature)

    assert bound is not None
    assert [param.name for param in bound.visible_params] == [
        "input",
        "weight",
        "kernel_size",
        "stride",
        "padding",
        "out",
    ]

    source = module._generate_torch_method_source("slow_conv3d", bound)

    assert "std::optional<Tensor> bias" not in source
    assert "c10::optional<at::Tensor>{}" in source
    assert "at::slow_conv3d_out" in source


def test_existing_base_overload_can_omit_defaulted_schema_params():
    module = _load_generator_module()
    op = module._parse_func(
        "add.Tensor(Tensor self, Tensor other, *, Scalar alpha=1, "
        "Tensor(a!) out) -> Tensor(a!)"
    )
    signature = [
        ("const Tensor", "input"),
        ("const Tensor", "other"),
        ("Tensor", "out"),
    ]

    bound = module._bind_base_signature(op, signature)

    assert bound is not None

    source = module._generate_torch_method_source("add", bound)

    assert "double alpha" not in source
    assert "const auto device_index = out.device().index();" in source
    assert "device_index_)" not in source
    assert "at::add_out(at_out, at_self, at_other, 1)" in source


def test_existing_base_overload_matches_by_name_when_types_repeat():
    module = _load_generator_module()
    op = module._parse_func(
        "std(Tensor input, int[1]? dim=None, bool unbiased=True, "
        "bool keepdim=False, *, Tensor(a!) out) -> Tensor(a!)"
    )
    signature = [
        ("Tensor", "input"),
        ("bool", "keepdim"),
        ("Tensor", "out"),
    ]

    bound = module._bind_base_signature(op, signature)

    assert bound is not None
    assert [param.name for param in bound.visible_params] == [
        "input",
        "keepdim",
        "out",
    ]

    source = module._generate_torch_method_source("std", bound)

    assert "c10::optional<at::IntArrayRef>{}, true, keepdim" in source
    assert "unbiased" not in source


def test_existing_base_overload_can_group_tensor_inputs_before_attributes():
    module = _load_generator_module()
    op = module._parse_func(
        "gather.out(Tensor self, int dim, Tensor index, bool sparse_grad=False, "
        "*, Tensor(a!) out) -> Tensor(a!)"
    )
    signature = [
        ("Tensor", "input"),
        ("Tensor", "index"),
        ("int64_t", "dim"),
        ("bool", "sparse_grad"),
        ("Tensor", "out"),
    ]

    bound = module._bind_base_signature(op, signature)

    assert bound is not None
    assert [param.api_name for param in bound.visible_params] == [
        "input",
        "index",
        "dim",
        "sparse_grad",
        "out",
    ]

    assert [
        next(
            index
            for index, binding in enumerate(bound.param_bindings)
            if binding is param
        )
        for param in bound.visible_params
    ] == [0, 2, 1, 3, 4]

    source = module._generate_torch_method_source("gather", bound)

    assert "at::gather_out(at_out, at_self, dim, at_index, sparse_grad)" in source


def test_rrelu_with_noise_base_order_preserves_aten_call_order():
    module = _load_generator_module()
    op = module._parse_func(
        "rrelu_with_noise.out(Tensor self, Tensor(b!) noise, Scalar lower=0.125, "
        "Scalar upper=0.3333333333333333, bool training=False, "
        "Generator? generator=None, *, Tensor(a!) out) -> Tensor(a!)"
    )
    signature = [
        ("Tensor", "input"),
        ("double", "lower"),
        ("double", "upper"),
        ("bool", "training"),
        ("Tensor", "out"),
        ("Tensor", "noise"),
    ]

    bound = module._bind_base_signature(op, signature)

    assert bound is not None
    assert [param.api_name for param in bound.visible_params] == [
        "input",
        "lower",
        "upper",
        "training",
        "out",
        "noise",
    ]
    assert [
        next(
            index
            for index, binding in enumerate(bound.param_bindings)
            if binding is param
        )
        for param in bound.visible_params
    ] == [0, 2, 3, 4, 6, 1]

    source = module._generate_torch_method_source("rrelu_with_noise", bound)

    assert "Tensor out, Tensor noise" in source
    assert (
        "at::rrelu_with_noise_out(at_out, at_self, at_noise, lower, upper, "
        "training, c10::optional<at::Generator>{})" in source
    )


def test_write_text_if_changed_preserves_unchanged_mtime(tmp_path):
    module = _load_generator_module()
    path = tmp_path / "generated.cc"
    path.write_text("same\n")
    before = path.stat().st_mtime_ns

    assert module._write_text_if_changed(path, "same\n") is False
    assert path.stat().st_mtime_ns == before

    assert module._write_text_if_changed(path, "different\n") is True
    assert path.read_text() == "different\n"
    assert path.stat().st_mtime_ns >= before


def test_remove_stale_files_keeps_expected_outputs(tmp_path):
    module = _load_generator_module()
    root = tmp_path / "generated"
    keep = root / "torch" / "keep.cc"
    stale = root / "torch" / "stale.cc"
    nested_stale = root / "base" / "stale.h"
    keep.parent.mkdir(parents=True)
    nested_stale.parent.mkdir(parents=True)
    keep.write_text("keep\n")
    stale.write_text("stale\n")
    nested_stale.write_text("stale\n")

    module._remove_stale_files(root, {keep})

    assert keep.exists()
    assert not stale.exists()
    assert not nested_stale.exists()
    assert not (root / "base").exists()


def test_inplace_schema_can_bind_to_explicit_output_signature():
    module = _load_generator_module()
    op = module._parse_func("fill_.Scalar(Tensor(a!) self, Scalar value) -> Tensor(a!)")
    signature = [
        ("Tensor", "input"),
        ("double", "value"),
        ("Tensor", "out"),
    ]

    bound = module._bind_base_signature(op, signature)

    assert bound is not None
    assert bound.explicit_inplace_out is not None
    assert [param.api_name for param in bound.visible_params] == [
        "input",
        "value",
        "out",
    ]
    assert bound.out_params[0].api_name == "out"

    source = module._generate_torch_method_source("fill", bound)

    assert "const auto device_index = out.device().index();" in source
    assert "const_cast<void*>(input.data())" in source
    assert "auto at_out = ToAtenTensor" in source
    assert "at_out.copy_(at_self);" in source
    assert "at_out.fill_(value);" in source

    implicit_bound = module._bind_base_signature(op, signature[:-1])

    assert implicit_bound is not None
    assert implicit_bound.explicit_inplace_out is None

    implicit_source = module._generate_torch_method_source("fill", implicit_bound)
    assert "at_self.fill_(value);" in implicit_source
