# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  smoketest:
    runs-on: self-hosted
    env:
      MODEL_LIST: DeepSeek-R1-Distill-Qwen-1.5B
      IMAGE: 2.2.RC1-800I-A2-py311-openeuler24.03-lts
    steps:
      - name: Trigger Ascend NPU Smoke Test job
        run: |
            echo "Smoke Test Starting..."
            echo "MODEL_LIST = $MODEL_LIST"
            echo "Version = $IMAGE"
            set -m
            cd /home/zkjh
            if [ ! -d Ascend_910_Test ]; then
              mkdir -p Ascend_910_Test
            fi
            cd Ascend_910_Test
            mkdir ${{ github.run_id }}
            cd ${{ github.run_id }}
            git init
            git remote add origin git@github.com:Vincent777/ci_autotest.git
            git fetch --depth=1 origin main
            git show orgiin/main:ascend_test_suite/daemon.sh > daemon.sh
            chmod a+x daemon.sh
            ./daemon.sh \
              Ascend  \
              Smoke \
              MindIE  \
              ${MODEL_LIST} \
              ${{ github.run_id }}  \
              ${IMAGE}
